version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg-dice
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diceroll
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-dice
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/diceroll
    ports:
      - '3000:3000'
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
